<?php
$pageTitle='Workspace do Projeto | CEPIN-CIS';$bodyClass='app-page project-workspace-page';
require_once 'controllers/AuthController.php';require_once 'models/Project.php';require_once 'models/ProjectWorkspace.php';
$auth=new AuthController();$auth->requireAuth();$user=$auth->getCurrentUser();$pm=new ProjectManager();$wm=new ProjectWorkspaceManager();$id=trim((string)($_GET['id']??''));$project=$pm->getProject($id);if(!$project){header('Location: dashboard.php');exit;}if(!$wm->canViewWorkspace($project,$user)){http_response_code(403);include 'includes/header.php';echo '<main class="page-shell"><section class="panel-card"><h1>Acesso negado</h1><p>Voce nao faz parte deste workspace.</p></section></main>';include 'includes/footer.php';exit;}
$isManager=$auth->isAdmin($user)||(int)$user['id']===(int)$project['user_id'];$message='';$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){$action=(string)($_POST['action']??'');$csrf=(string)($_POST['csrf']??'');if(empty($_SESSION['workspace_csrf']))$_SESSION['workspace_csrf']=bin2hex(random_bytes(16));if(!hash_equals($_SESSION['workspace_csrf'],$csrf))$errors[]='Sessao expirada.';else switch($action){case 'upload_document':$r=$wm->uploadDocument($id,(int)$user['id'],$_FILES['document']??null);$message=$r['success']?'Documento enviado para analise.':'';$errors=$r['errors']??[];break;case 'timeline':$r=$wm->addTimelineEvent($id,(int)$user['id'],$_POST,$_FILES['attachment']??null);$message=$r['success']?'Evento adicionado.':'';$errors=$r['errors']??[];break;case 'delete_timeline':if($isManager&&$wm->deleteTimelineEvent((string)$_POST['event_id'],(int)$user['id']))$message='Evento removido.';else $errors[]='Nao foi possivel remover o evento.';break;case 'add_collaborator':if($isManager){$r=$wm->addCollaborator($id,(int)$_POST['user_id'],(string)($_POST['role']??'collaborator'));$message=$r?'Colaborador adicionado.':'';if(!$r)$errors[]='Nao foi possivel adicionar o colaborador.';}else $errors[]='Apenas o responsavel pode gerenciar colaboradores.';break;case 'remove_collaborator':if($isManager&&$wm->removeCollaborator($id,(int)$_POST['user_id']))$message='Colaborador removido.';else $errors[]='Nao foi possivel remover o colaborador.';break;case 'authenticate':if($isManager&&$wm->setAuthentication($id,(int)$user['id'],(int)$_POST['document_id'],(string)($_POST['status']??'authenticated'),trim((string)($_POST['notes']??''))))$message='Status de autenticacao atualizado.';else $errors[]='Nao foi possivel atualizar a autenticacao.';break;}}
$_SESSION['workspace_csrf']=$_SESSION['workspace_csrf']??bin2hex(random_bytes(16));$docs=$wm->listDocuments($id);$timeline=$wm->getProjectTimeline($id);$collabs=$wm->getProjectCollaborators($id);$allUsers=$auth->listUsers();$authStatus=$wm->getAuthenticationStatus($project);
include 'includes/header.php';
?>
<main class="page-shell app-shell"><section class="panel-card"><p class="eyebrow">Workspace</p><h1><?php echo htmlspecialchars($project['title']); ?></h1><p><?php echo htmlspecialchars($project['description']); ?></p><?php if($message):?><div class="mensagem sucesso"><?php echo htmlspecialchars($message);?></div><?php endif;?><?php foreach($errors as $e):?><div class="mensagem erro"><?php echo htmlspecialchars($e);?></div><?php endforeach;?></section>
<section class="dashboard-grid">
<article class="panel-card"><h2>Documentos</h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?php echo htmlspecialchars($_SESSION['workspace_csrf']);?>"><input type="hidden" name="action" value="upload_document"><input type="file" name="document" required><button class="dashboard-btn" type="submit">Enviar documento</button></form><?php foreach($docs as $d):?><div class="panel-card"><strong><?php echo htmlspecialchars($d['original_name']);?></strong><span><?php echo htmlspecialchars($d['status']);?></span><a href="project-file.php?kind=document&id=<?php echo (int)$d['id'];?>">Abrir</a><?php if($isManager):?><form method="post" style="display:inline"><input type="hidden" name="csrf" value="<?php echo htmlspecialchars($_SESSION['workspace_csrf']);?>"><input type="hidden" name="action" value="authenticate"><input type="hidden" name="document_id" value="<?php echo (int)$d['id'];?>"><select name="status"><option value="authenticated">Autenticado</option><option value="pending">Em analise</option><option value="rejected">Rejeitado</option></select><input name="notes" placeholder="Observacao"><button type="submit">Atualizar</button></form><?php endif;?></div><?php endforeach;?></article>
<article class="panel-card"><h2>Timeline</h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?php echo htmlspecialchars($_SESSION['workspace_csrf']);?>"><input type="hidden" name="action" value="timeline"><input name="title" placeholder="Titulo" required><textarea name="description" placeholder="Descricao" required></textarea><input type="date" name="event_date" value="<?php echo date('Y-m-d');?>" required><select name="event_type"><option value="update">Atualizacao</option><option value="milestone">Marco</option><option value="meeting">Reuniao</option><option value="result">Resultado</option><option value="publication">Publicacao</option></select><input type="file" name="attachment"><button class="dashboard-btn" type="submit">Adicionar evento</button></form><?php foreach($timeline as $e):?><div class="panel-card"><small><?php echo htmlspecialchars($e['event_date']);?></small><h3><?php echo htmlspecialchars($e['title']);?></h3><p><?php echo nl2br(htmlspecialchars($e['description']));?></p><?php if(!empty($e['attachment_path'])):?><a href="project-file.php?kind=timeline&id=<?php echo urlencode($e['id']);?>">Anexo</a><?php endif;?><?php if($isManager):?><form method="post"><input type="hidden" name="csrf" value="<?php echo htmlspecialchars($_SESSION['workspace_csrf']);?>"><input type="hidden" name="action" value="delete_timeline"><input type="hidden" name="event_id" value="<?php echo htmlspecialchars($e['id']);?>"><button type="submit">Remover</button></form><?php endif;?></div><?php endforeach;?></article>
</section>
<section class="dashboard-grid"><article class="panel-card"><h2>Equipe</h2><p>Status de autenticacao: <strong><?php echo htmlspecialchars($authStatus['label']);?></strong></p><?php if($isManager):?><form method="post"><input type="hidden" name="csrf" value="<?php echo htmlspecialchars($_SESSION['workspace_csrf']);?>"><input type="hidden" name="action" value="add_collaborator"><select name="user_id" required><?php foreach($allUsers as $u): if((int)$u['id']===(int)$project['user_id'])continue;?><option value="<?php echo (int)$u['id'];?>"><?php echo htmlspecialchars($u['fullname'].' (@'.$u['username'].')');?></option><?php endforeach;?></select><select name="role"><option value="collaborator">Colaborador</option><option value="project_admin">Admin do projeto</option></select><button type="submit">Adicionar</button></form><?php endif;?><?php foreach($collabs as $c):$cu=$auth->getUserById((int)$c['user_id']);?><div><strong><?php echo htmlspecialchars($cu['fullname']??$cu['username']??'Usuario');?></strong> — <?php echo htmlspecialchars($c['role']);?><?php if($isManager):?><form method="post" style="display:inline"><input type="hidden" name="csrf" value="<?php echo htmlspecialchars($_SESSION['workspace_csrf']);?>"><input type="hidden" name="action" value="remove_collaborator"><input type="hidden" name="user_id" value="<?php echo (int)$c['user_id'];?>"><button type="submit">Remover</button></form><?php endif;?></div><?php endforeach;?></article></section></main><?php include 'includes/footer.php';?>
