<?php
require_once __DIR__ . '/../bootstrap.php';
class ProjectWorkspaceManager
{
    private PDO $pdo;
    private string $documentDir;
    private string $timelineDir;
    public function __construct(){ $this->pdo=db();$this->documentDir=__DIR__.'/../uploads/projects/documents';$this->timelineDir=__DIR__.'/../uploads/projects/timeline';foreach([$this->documentDir,$this->timelineDir] as $d){if(!is_dir($d))mkdir($d,0775,true);}}
    public function canViewWorkspace(array $project,?array $user):bool{if(!$user)return false;if((int)($user['role_rank']??0)>=100)return true;$uid=(int)($user['id']??0);if($uid===(int)($project['user_id']??$project['owner_user_id']??0))return true;$s=$this->pdo->prepare('SELECT 1 FROM project_collaborators WHERE project_id=? AND user_id=? LIMIT 1');$s->execute([(string)$project['id'],$uid]);return (bool)$s->fetchColumn();}
    public function getProjectCollaborators(string $projectId):array{$s=$this->pdo->prepare('SELECT * FROM project_collaborators WHERE project_id=? ORDER BY created_at');$s->execute([$projectId]);return $s->fetchAll();}
    public function addCollaborator(string $projectId,int $userId,string $role='collaborator'):bool{$s=$this->pdo->prepare("INSERT INTO project_collaborators(project_id,user_id,role) VALUES(?,?,?) ON DUPLICATE KEY UPDATE role=VALUES(role)");return $s->execute([$projectId,$userId,$role]);}
    public function removeCollaborator(string $projectId,int $userId):bool{$s=$this->pdo->prepare('DELETE FROM project_collaborators WHERE project_id=? AND user_id=?');$s->execute([$projectId,$userId]);return $s->rowCount()>0;}
    public function getProjectTimeline(string $projectId):array{$s=$this->pdo->prepare('SELECT * FROM project_timeline_events WHERE project_id=? AND deleted_at IS NULL ORDER BY event_date DESC,created_at DESC');$s->execute([$projectId]);return $s->fetchAll();}
    public function getTimelineTypeLabel(string $type):string{return ['update'=>'Atualizacao','milestone'=>'Marco','meeting'=>'Reuniao','result'=>'Resultado','publication'=>'Publicacao'][$type]??'Atualizacao';}
    public function addTimelineEvent(string $projectId,int $authorId,array $data,?array $file=null):array{$title=trim((string)($data['title']??''));$desc=trim((string)($data['description']??''));$date=trim((string)($data['event_date']??date('Y-m-d')));$type=(string)($data['event_type']??'update');$e=[];if($title==='')$e[]='Titulo e obrigatorio.';if($desc==='')$e[]='Descricao e obrigatoria.';if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))$e[]='Data invalida.';if($e)return ['success'=>false,'errors'=>$e];$attachment=$this->storeAttachment($file,$this->timelineDir,'timeline');if(!$attachment['success'])return $attachment;$id=uniqid('tl_');$s=$this->pdo->prepare('INSERT INTO project_timeline_events(id,project_id,title,description,event_date,event_type,author_user_id,attachment_original_name,attachment_stored_name,attachment_path,attachment_mime_type,attachment_size_bytes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$id,$projectId,$title,$desc,$date,$type,$authorId,$attachment['original_name']??null,$attachment['stored_name']??null,$attachment['path']??null,$attachment['mime_type']??null,$attachment['size_bytes']??null]);$this->history($id,$projectId,$authorId,'created',null,['title'=>$title,'description'=>$desc,'event_date'=>$date,'event_type'=>$type]);return ['success'=>true,'event'=>$this->getTimelineEvent($id)];}
    public function deleteTimelineEvent(string $id,int $actorId):bool{$e=$this->getTimelineEvent($id);if(!$e)return false;$s=$this->pdo->prepare('UPDATE project_timeline_events SET deleted_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?');$s->execute([$id]);$this->history($id,(string)$e['project_id'],$actorId,'deleted',$e,null);return $s->rowCount()>0;}
    public function getTimelineEvent(string $id):?array{$s=$this->pdo->prepare('SELECT * FROM project_timeline_events WHERE id=? LIMIT 1');$s->execute([$id]);return $s->fetch()?:null;}
    public function listDocuments(string $projectId):array{$s=$this->pdo->prepare('SELECT * FROM project_documents WHERE project_id=? ORDER BY created_at DESC');$s->execute([$projectId]);return $s->fetchAll();}
    public function uploadDocument(string $projectId,int $userId,?array $file):array{if(!is_array($file)||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)return ['success'=>false,'errors'=>['Selecione um arquivo valido.']];if((int)($file['size']??0)>25*1024*1024)return ['success'=>false,'errors'=>['O arquivo deve ter no maximo 25 MB.']];$stored=$this->storeAttachment($file,$this->documentDir,'document');if(!$stored['success'])return ['success'=>false,'errors'=>[$stored['error']]];$s=$this->pdo->prepare('INSERT INTO project_documents(project_id,uploaded_by_user_id,original_name,stored_name,storage_path,mime_type,extension,size_bytes,sha256_hash,status) VALUES(?,?,?,?,?,?,?,?,?,\'pending\')');$s->execute([$projectId,$userId,$stored['original_name'],$stored['stored_name'],$stored['path'],$stored['mime_type'],$stored['extension'],$stored['size_bytes'],hash_file('sha256',$file['tmp_name'])]);return ['success'=>true,'document'=>$this->getDocument((int)$this->pdo->lastInsertId())];}
    public function getDocument(int $id):?array{$s=$this->pdo->prepare('SELECT * FROM project_documents WHERE id=? LIMIT 1');$s->execute([$id]);return $s->fetch()?:null;}
    public function setAuthentication(string $projectId,int $actorId,int $documentId,string $status='authenticated',string $notes=''):bool{$doc=$this->getDocument($documentId);if(!$doc||$doc['project_id']!==$projectId)return false;$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('UPDATE projects SET authentication_status=?,authenticated_document_id=?,authenticated_at=? WHERE id=?');$s->execute([$status,$status==='authenticated'?$documentId:null,$status==='authenticated'?date('Y-m-d H:i:s'):null,$projectId]);$h=$this->pdo->prepare('INSERT INTO project_authentication_history(project_id,document_id,actor_user_id,action,notes) VALUES(?,?,?,?,?)');$h->execute([$projectId,(string)$documentId,$actorId,$status,$notes]);$this->pdo->commit();return true;}catch(Throwable $e){$this->pdo->rollBack();return false;}}
    public function getAuthenticationStatus(array $project):array{$k=(string)($project['authentication_status']??'missing');return ['status'=>$k,'label'=>['missing'=>'Sem documentacao','pending'=>'Em analise','authenticated'=>'Autenticado','rejected'=>'Rejeitado'][$k]??'Sem documentacao'];}
    public function createInvite(string $projectId,int $invitedUserId,int $byUserId,string $role='collaborator'):array{$id=uniqid('invite_');try{$s=$this->pdo->prepare('INSERT INTO project_collaboration_invites(id,project_id,invited_user_id,invited_by_user_id,role,status) VALUES(?,?,?,?,?,\'pending\')');$s->execute([$id,$projectId,$invitedUserId,$byUserId,$role]);$this->notify($invitedUserId,'project_invite','Convite para projeto','Voce recebeu um convite para colaborar em um projeto.',$projectId,'project-workspace.php?id='.rawurlencode($projectId),$byUserId);return ['success'=>true,'invite'=>$this->getInvite($id)];}catch(Throwable $e){return ['success'=>false,'errors'=>['Ja existe um convite pendente para este usuario.']];}}
    public function getInvite(string $id):?array{$s=$this->pdo->prepare('SELECT * FROM project_collaboration_invites WHERE id=?');$s->execute([$id]);return $s->fetch()?:null;}
    public function getPendingInvitesForUser(int $uid):array{$s=$this->pdo->prepare('SELECT * FROM project_collaboration_invites WHERE invited_user_id=? AND status=\'pending\' ORDER BY created_at DESC');$s->execute([$uid]);return $s->fetchAll();}
    public function respondInvite(string $id,int $uid,string $response):bool{$i=$this->getInvite($id);if(!$i||$i['invited_user_id']!=$uid||!in_array($response,['accepted','rejected'],true))return false;$s=$this->pdo->prepare('UPDATE project_collaboration_invites SET status=?,responded_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?');$s->execute([$response,$id]);if($response==='accepted')$this->addCollaborator($i['project_id'],$uid,$i['role']);return true;}
    public function listNotifications(int $uid,int $limit=30):array{$s=$this->pdo->prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT '.max(1,min(100,(int)$limit))); $s->execute([$uid]);return $s->fetchAll();}
    public function unreadNotificationCount(int $uid):int{$s=$this->pdo->prepare('SELECT COUNT(*) FROM notifications WHERE user_id=? AND read_at IS NULL');$s->execute([$uid]);return (int)$s->fetchColumn();}
    public function markNotificationRead(string $id,int $uid):bool{$s=$this->pdo->prepare('UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?');$s->execute([$id,$uid]);return $s->rowCount()>0;}
    public function notify(int $uid,string $type,string $title,string $body='',?string $projectId=null,?string $url=null,?int $actor=null):void{$s=$this->pdo->prepare('INSERT INTO notifications(id,user_id,type,title,body,project_id,target_url,actor_user_id) VALUES(?,?,?,?,?,?,?,?)');$s->execute([uniqid('ntf_'),$uid,$type,$title,$body,$projectId,$url,$actor]);}
    private function history(string $event,string $project,int $actor,string $action,$before,$after):void{$s=$this->pdo->prepare('INSERT INTO project_timeline_history(id,event_id,project_id,actor_user_id,action,before_payload,after_payload) VALUES(?,?,?,?,?,?,?)');$s->execute([uniqid('tlh_'),$event,$project,$actor,$action,$before?json_encode($before,JSON_UNESCAPED_UNICODE):null,$after?json_encode($after,JSON_UNESCAPED_UNICODE):null]);}
    private function storeAttachment(?array $file,string $dir,string $prefix):array{if(!is_array($file)||($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return ['success'=>true];if(($file['error']??-1)!==UPLOAD_ERR_OK)return ['success'=>false,'error'=>'Falha no upload.'];$original=basename((string)$file['name']);$ext=strtolower(pathinfo($original,PATHINFO_EXTENSION));$mime=function_exists('mime_content_type')?(string)@mime_content_type($file['tmp_name']):'application/octet-stream';$stored=uniqid($prefix.'_').($ext!==''?'.'.$ext:'');if(!move_uploaded_file($file['tmp_name'],$dir.'/'.$stored))return ['success'=>false,'error'=>'Nao foi possivel salvar o arquivo.'];$rel='./uploads/projects/'.($prefix==='timeline'?'timeline/':'documents/').$stored;return ['success'=>true,'original_name'=>$original,'stored_name'=>$stored,'path'=>$rel,'mime_type'=>$mime,'extension'=>$ext,'size_bytes'=>(int)$file['size']];}
}
